service: cf-worker-project

frameworkVersion: '2'

package:
  exclude:
    - .github/**

useDotenv: true

provider:
  name: cloudflare
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}
  environment:
    CLOUDFLARE_AUTH_KEY: ${env:CLOUDFLARE_AUTH_KEY}
    CLOUDFLARE_AUTH_EMAIL: ${env:CLOUDFLARE_AUTH_EMAIL}

plugins:
  - serverless-cloudflare-workers

functions:
  greet:
    name: greet
    script: dist/worker # worker.js
    resources:
      kv:
        - variable: ENV
          namespace: ENV
    events:
      - http:
          url: mleyb.uk/greet/*
          method: GET
          headers:
            foo: bar
            x-client-data: value
